/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "add.h"
#include<stdio.h>
#include<stdlib.h>

void
addprg_1(char *host,int a,int b)
{
	CLIENT *clnt;
	int  *result_1;
	intpair  add_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, ADDPRG, ADDVER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	add_1_arg.a = a;
	add_1_arg.b = b;
	result_1 = add_1(&add_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
		printf("Result is %d\n",*(result_1));
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	int a,b;
	if (argc < 3) {
		printf ("usage: %s server_host two numbers\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	/*if((a=atoi(argv[2]))==0 && *argv[2]!='0'){
		fprintf(stderr,"InvalidValue=%s\n",argv[2]);
		exit(1);
	}
	if((b=atoi(argv[3]))==0 && *argv[3]!='0'){
		fprintf(stderr,"InvalidValue=%s\n",argv[3]);
		exit(1);
	}*/
	addprg_1(host,atoi(argv[2]),atoi(argv[3]));
	exit(0);
}
