/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DATE_H_RPCGEN
#define _DATE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define DATEPRG 0x1968
#define DATEVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define date 1
extern  char ** date_1(void *, CLIENT *);
extern  char ** date_1_svc(void *, struct svc_req *);
extern int dateprg_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define date 1
extern  char ** date_1();
extern  char ** date_1_svc();
extern int dateprg_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_DATE_H_RPCGEN */
