/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ECHO_H_RPCGEN
#define _ECHO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define ECHOPRG 0x068
#define ECHOVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define scho 1
extern  char ** scho_1(char **, CLIENT *);
extern  char ** scho_1_svc(char **, struct svc_req *);
extern int echoprg_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define scho 1
extern  char ** scho_1();
extern  char ** scho_1_svc();
extern int echoprg_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ECHO_H_RPCGEN */
